services:
  user-service:
    build: ./user-services
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongo:27017/user_service_db
    networks:
      - backend

  event-service:
    build: ./event-services
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      DATABASE_URL: mongodb://mongo:27017/eventsdb
    networks:
      - backend

  booking-service:
    build: ./booking-services
    ports:
      - "5002:5002"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:pass@postgres:5432/bookings_db
    networks:
      - backend

  notification-service:
    build: ./notifications-services
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      DATABASE_URL: mongodb://mongo:27017/notificationsdb
    networks:
      - backend

  frontend-service:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - user-service
      - event-service
      - booking-service
      - notification-service
    networks:
      - backend
      - frontend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: users_db
      PGPORT: 5432
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U myuser -d users_db -h localhost -p 5432"]
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "port=5432"]
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo_data:/data/db

networks:
  backend:
    driver: bridge
    name: cs4067-assgt-eventbooking-i220857-Inam-Ullah-master_backend
  frontend:
    driver: bridge
    name: cs4067-assgt-eventbooking-i220857-Inam-Ullah-master_frontend

volumes:
  postgres_data:
  mongo_data:
