name: Jira Issue Automation

on:
  push:
    branches:
      - main
      - develop
      - feature/*

jobs:
  update-jira:
    runs-on: ubuntu-latest # GitHub Actions can run on Ubuntu, even on Windows environments

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Extract Jira Issue Keys from Commit Messages
        id: extract-issues
        run: |
          ISSUES=$(git log --format=%B -n 1 | grep -oE 'CE20I-[0-9]+' | uniq)
          echo "Found Jira Issues: $ISSUES"
          echo "ISSUES=$ISSUES" >> $GITHUB_ENV

      - name: Move Issues to In Progress
        if: env.ISSUES != ''
        run: |
          for ISSUE in $ISSUES; do
            curl --request POST \
              --url "https://your-jira-instance.atlassian.net/rest/api/3/issue/$ISSUE/transitions" \
              --user "$JIRA_USER:$JIRA_API_TOKEN" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data '{
                "transition": { "id": "11" }  # Replace with your 'In Progress' transition ID
              }'
          done
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Move Issues to Done if Fixed
        if: env.ISSUES != '' && contains(github.event.head_commit.message, 'fix') || contains(github.event.head_commit.message, 'resolve')
        run: |
          for ISSUE in $ISSUES; do
            curl --request POST \
              --url "https://your-jira-instance.atlassian.net/rest/api/3/issue/$ISSUE/transitions" \
              --user "$JIRA_USER:$JIRA_API_TOKEN" \
              --header "Accept: application/json" \
              --header "Content-Type: application/json" \
              --data '{
                "transition": { "id": "21" }  # Replace with your 'Done' transition ID
              }'
          done
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
